<a href="https://colab.research.google.com/github/rosa2070/TensorFlow01_25/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## TensorFlow로 알아보는 딥러닝



In [ ]:
import tensorflow as tf
import pandas as pd

In [ ]:
data = {
    '창업연차' : [4, 5, 6, 7, 8],
    '매출액(억)' : [8, 10, 12, 14, 16]
}

df = pd.DataFrame(data)
df

창업연차  매출액(억)
0     4       8
1     5      10
2     6      12
3     7      14
4     8      16

In [ ]:
독립 = df[['창업연차']] # 원인
종속 = df[['매출액(억)']] # 결과

독립.shape, 종속.shape

((5, 1), (5, 1))

In [ ]:
## 모델 준비(y = wx + b)
X = tf.keras.layers.Input(shape=[1]) # 독립변수의 col
Y = tf.keras.layers.Dense(1)(X) # 종속변수의 col
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse') 
#MSE(mean squared error) : 회귀 용도의 딥러닝 모델을 훈련시킬 때 사용되는 손실 함수

In [ ]:
model.fit(독립, 종속, epochs = 10)

Epoch 1/10
1/1 [==============================] - 1s 520ms/step - loss: 160.4822
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 159.9109
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 159.4973
Epoch 4/10
1/1 [==============================] - 0s 4ms/step - loss: 159.1517
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 158.8453
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: 158.5648
Epoch 7/10
1/1 [==============================] - 0s 4ms/step - loss: 158.3029
Epoch 8/10
1/1 [==============================] - 0s 4ms/step - loss: 158.0550
Epoch 9/10
1/1 [==============================] - 0s 4ms/step - loss: 157.8179
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 157.5895


In [ ]:
model.predict([10])

array([[-0.36012468]], dtype=float32)

In [ ]:
model.predict(독립)

array([[-0.13366769],
       [-0.17141052],
       [-0.20915335],
       [-0.24689619],
       [-0.28463903]], dtype=float32)

In [ ]:
#y = wx + b

model.get_weights()

[array([[-0.03774283]], dtype=float32), array([0.01730363], dtype=float32)]

In [ ]:
-0.03774283 * 10 + 0.01730363

-0.36012467

In [ ]:
model.fit(독립, 종속, epochs = 10000, verbose=0)
model.fit(독립, 종속, epochs = 10)

Epoch 1/10
1/1 [==============================] - 0s 4ms/step - loss: 1.2749e-05
Epoch 2/10
1/1 [==============================] - 0s 8ms/step - loss: 1.2750e-05
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 1.2749e-05
Epoch 4/10
1/1 [==============================] - 0s 3ms/step - loss: 1.2750e-05
Epoch 5/10
1/1 [==============================] - 0s 4ms/step - loss: 1.2749e-05
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 1.2750e-05
Epoch 7/10
1/1 [==============================] - 0s 3ms/step - loss: 1.2749e-05
Epoch 8/10
1/1 [==============================] - 0s 3ms/step - loss: 1.2750e-05
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 1.2749e-05
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 1.2750e-05


In [ ]:
model.predict(독립)

array([[ 8.002501],
       [10.003   ],
       [12.0035  ],
       [14.004   ],
       [16.0045  ]], dtype=float32)

In [ ]:
model.predict([10])

array([[20.005499]], dtype=float32)

In [ ]:
#y = wx + b

model.get_weights()

[array([[2.0004997]], dtype=float32), array([0.00050134], dtype=float32)]

In [ ]:
2.0004997 * 10 + 0.00050134

20.005498340000003

In [11]:
import tensorflow as tf
import pandas as pd

In [12]:
from sklearn import datasets

iris = datasets.load_iris()
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [13]:
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
dataset = pd.read_csv(path)
dataset.head()
dataset.tail()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭         품종
145   6.7  3.0    5.2   2.3  virginica
146   6.3  2.5    5.0   1.9  virginica
147   6.5  3.0    5.2   2.0  virginica
148   6.2  3.4    5.4   2.3  virginica
149   5.9  3.0    5.1   1.8  virginica

In [14]:
encoded = pd.get_dummies(dataset)
encoded.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [18]:
print(encoded.columns)

독립 = encoded[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = encoded[['품종_setosa', '품종_versicolor', '품종_virginica']]

독립.shape, 종속.shape

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


((150, 4), (150, 3))

In [20]:
## 모델 준비
X = tf.keras.layers.Input(shape=[4]) # 독립변수의 col
Y = tf.keras.layers.Dense(3, activation='softmax')(X) # 종속변수의 col
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [21]:
#모델 학습
model.fit(독립, 종속, epochs = 10000, verbose=0)
model.fit(독립, 종속, epochs = 10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0539 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0539 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0539 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0540 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0536 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0536 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0536 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0539 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0542 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0540 - accuracy: 0.9800


In [23]:
model.predict(독립)

array([[1.00000000e+00, 2.57876255e-11, 2.12938250e-24],
       [1.00000000e+00, 2.61796629e-09, 2.84739033e-21],
       [1.00000000e+00, 2.65611005e-10, 1.29325276e-22],
       [1.00000000e+00, 6.93937174e-09, 1.70666893e-20],
       [1.00000000e+00, 1.42287362e-11, 9.97633240e-25],
       [1.00000000e+00, 1.67136097e-10, 3.31701748e-23],
       [1.00000000e+00, 7.02970349e-10, 7.84014952e-22],
       [1.00000000e+00, 2.24522595e-10, 5.81466660e-23],
       [1.00000000e+00, 1.94688923e-08, 1.12747199e-19],
       [1.00000000e+00, 9.34558542e-10, 4.26137966e-22],
       [1.00000000e+00, 7.26438918e-12, 1.98107255e-25],
       [1.00000000e+00, 1.07859988e-09, 7.43889169e-22],
       [1.00000000e+00, 9.03661923e-10, 4.98230462e-22],
       [1.00000000e+00, 1.08461920e-10, 5.03301935e-23],
       [1.00000000e+00, 8.69890047e-15, 5.97987067e-30],
       [1.00000000e+00, 1.44503658e-13, 6.52784518e-28],
       [1.00000000e+00, 2.06144954e-12, 6.08096079e-26],
       [1.00000000e+00, 9.45274

In [25]:
model.predict([[5.1, 3.5, 1.4, 0.2]])

array([[1.0000000e+00, 2.5787626e-11, 2.1293823e-24]], dtype=float32)

In [26]:
model.get_weights()

[array([[  4.2172365,   1.8642482,  -0.650338 ],
        [ 10.120681 ,   1.8213624,  -2.3289404],
        [-12.575324 ,  -1.5868224,   3.1788273],
        [-17.023052 ,  -4.033099 ,   5.2754383]], dtype=float32),
 array([ 6.7204065,  5.405242 , -5.90301  ], dtype=float32)]

## 히든레이어

In [32]:
data = {
    '창업연차' : [4, 5, 6, 7, 8],
    '직원수' : [10, 20, 30, 40, 50],
    '기업가치' : [80, 200, 360, 540, 800]
}

df = pd.DataFrame(data)
df

창업연차  직원수  기업가치
0     4   10    80
1     5   20   200
2     6   30   360
3     7   40   540
4     8   50   800

In [34]:
9 * 60 * 2
8 * 50 * 2

800

In [43]:
독립 = df[['창업연차','직원수']]
종속 = df[['기업가치']]

독립.shape, 종속.shape

((5, 2), (5, 1))

In [46]:
## 모델 준비
X = tf.keras.layers.Input(shape=[2]) # 독립변수의 col
Y = tf.keras.layers.Dense(1)(X) # 종속변수의 col
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [49]:
## 모델 학습
model.fit(독립, 종속, epochs=100000, verbose=0) # epochs는 학습 수
model.fit(독립, 종속, epochs=10) # epochs는 학습 수

Epoch 1/10
1/1 [==============================] - 0s 3ms/step - loss: 1336.0010
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 1335.9996
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 1336.0010
Epoch 4/10
1/1 [==============================] - 0s 3ms/step - loss: 1335.9996
Epoch 5/10
1/1 [==============================] - 0s 3ms/step - loss: 1336.0010
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: 1335.9996
Epoch 7/10
1/1 [==============================] - 0s 3ms/step - loss: 1336.0010
Epoch 8/10
1/1 [==============================] - 0s 3ms/step - loss: 1335.9996
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 1336.0010
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 1335.9996


In [52]:
model.predict(독립)

array([[ 40.007565],
       [218.01303 ],
       [396.01852 ],
       [574.02405 ],
       [752.0295  ]], dtype=float32)

In [53]:
## 모델 준비
X = tf.keras.layers.Input(shape=[2]) # 독립변수의 col
H = tf.keras.layers.Dense(10, activation='swish')(X)
H = tf.keras.layers.Dense(10, activation='swish')(H)
H = tf.keras.layers.Dense(10, activation='swish')(H)
Y = tf.keras.layers.Dense(1)(H) # 종속변수의 col
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [54]:
## 모델 학습
model.fit(독립, 종속, epochs=100000, verbose=0) # epochs는 학습 수
model.fit(독립, 종속, epochs=10) # epochs는 학습 수

Epoch 1/10
1/1 [==============================] - 0s 5ms/step - loss: 2.2000
Epoch 2/10
1/1 [==============================] - 0s 7ms/step - loss: 2.0021
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 2.4544
Epoch 4/10
1/1 [==============================] - 0s 4ms/step - loss: 3.1338
Epoch 5/10
1/1 [==============================] - 0s 4ms/step - loss: 5.1603
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 8.0333
Epoch 7/10
1/1 [==============================] - 0s 4ms/step - loss: 15.0484
Epoch 8/10
1/1 [==============================] - 0s 3ms/step - loss: 19.1874
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 27.3369
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 15.0672


In [55]:
model.predict(독립)

array([[ 81.591286],
       [202.05536 ],
       [363.19235 ],
       [544.7741  ],
       [805.10394 ]], dtype=float32)

In [56]:
model.predict([[9, 60]])

array([[-451.9619]], dtype=float32)

In [57]:
model.get_weights()

[array([[-1.0340841 ,  0.42149827,  0.09148783, -1.13482   ,  1.2280333 ,
          0.67490256,  1.4455007 ,  0.9984629 , -1.2092096 ,  0.6543092 ],
        [ 0.34429187,  0.2625027 , -0.2101023 ,  0.18514164,  0.24328892,
         -0.13000163, -0.14183974,  0.04610476,  0.24022   , -0.13810618]],
       dtype=float32),
 array([-0.9863617 , -0.3904544 , -0.05599791, -0.6248551 ,  1.8050025 ,
         0.973321  ,  1.6638714 ,  1.3086858 , -2.2427886 ,  1.5078596 ],
       dtype=float32),
 array([[ 1.3331822 , -2.3969653 ,  1.9512482 , -0.48527038,  0.32241002,
          2.2300167 , -0.42173713,  1.2512158 , -1.0746397 , -0.27847168],
        [ 1.2638534 , -0.35276687,  0.991602  , -0.22762027, -0.24081661,
          1.734803  ,  0.09447683,  1.0835174 , -0.66308343, -0.13945186],
        [ 0.9976035 , -1.0707494 ,  1.4454435 ,  0.00908398, -0.25229055,
          1.5006504 , -0.0290439 ,  1.601239  , -0.39985603,  0.12029863],
        [ 1.3222141 ,  0.29050362,  1.432752  , -0.3903909 , 

In [58]:
df = pd.read_csv('오름데이터_csv.csv', encoding='utf-8')
df

name  loc  men  women  age
0       송악산    0   56     44   30
1      물영아리    0   54     46   20
2       이승이    0   61     39   30
3     머체왓숲길    0   47     53   50
4     성산일출봉    0   63     37   20
5        군산    0   65     35   30
6       용머리    0   59     41   20
7     따라비오름    0   56     44   30
8       영주산    0   49     51   30
9     백약이오름    0   42     58   20
10     붉은오름    0   50     50   30
11      고근산    0   50     50   50
12     거문오름    1   50     50   30
13     검은오름    1   46     54   20
14     궷물오름    1   54     46   20
15      다랑쉬    1   54     46   20
16      도두봉    1   48     52   20
17  물메(수산봉)    1   53     47   20
18      민오름    1   47     53   20
19   큰바리메오름    1   64     36   50
20     붉은오름    1   50     50   30
21     산굼부리    1   54     46   20
22     새별오름    1   50     50   20
23      서우봉    1   49     51   20
24      수월봉    1   55     45   20
25    아끈다랑쉬    1   50     50   30
26     아부오름    1   44     56   20
27     안돌오름    1   58     42   20
28    용눈이오름    1   42     58   20
29     저지오름    1   56     44   50
30     정물오름    1   62     38   40
31      지미봉    1   56     44   20

In [59]:
encoded = pd.get_dummies(df)
encoded.head()

loc  men  women  age  ...  name_저지오름  name_정물오름  name_지미봉  name_큰바리메오름
0    0   56     44   30  ...          0          0         0            0
1    0   54     46   20  ...          0          0         0            0
2    0   61     39   30  ...          0          0         0            0
3    0   47     53   50  ...          0          0         0            0
4    0   63     37   20  ...          0          0         0            0

[5 rows x 35 columns]

In [60]:
print(encoded.columns)

Index(['loc', 'men', 'women', 'age', 'name_거문오름', 'name_검은오름', 'name_고근산',
       'name_군산', 'name_궷물오름', 'name_다랑쉬', 'name_도두봉', 'name_따라비오름',
       'name_머체왓숲길', 'name_물메(수산봉)', 'name_물영아리', 'name_민오름', 'name_백약이오름',
       'name_붉은오름', 'name_산굼부리', 'name_새별오름', 'name_서우봉', 'name_성산일출봉',
       'name_송악산', 'name_수월봉', 'name_아끈다랑쉬', 'name_아부오름', 'name_안돌오름',
       'name_영주산', 'name_용눈이오름', 'name_용머리', 'name_이승이', 'name_저지오름',
       'name_정물오름', 'name_지미봉', 'name_큰바리메오름'],
      dtype='object')


In [61]:
독립 = encoded[['loc', 'men', 'women', 'age']]
종속 = encoded[['name_거문오름', 'name_검은오름', 'name_고근산',
       'name_군산', 'name_궷물오름', 'name_다랑쉬', 'name_도두봉', 'name_따라비오름',
       'name_머체왓숲길', 'name_물메(수산봉)', 'name_물영아리', 'name_민오름', 'name_백약이오름',
       'name_붉은오름', 'name_산굼부리', 'name_새별오름', 'name_서우봉', 'name_성산일출봉',
       'name_송악산', 'name_수월봉', 'name_아끈다랑쉬', 'name_아부오름', 'name_안돌오름',
       'name_영주산', 'name_용눈이오름', 'name_용머리', 'name_이승이', 'name_저지오름',
       'name_정물오름', 'name_지미봉', 'name_큰바리메오름']]

In [62]:
독립.shape, 종속.shape

((32, 4), (32, 31))

In [73]:
## 모델 준비

X = tf.keras.layers.Input(shape=[4]) # 독립변수의 col
Y = tf.keras.layers.Dense(31, activation='softmax')(X) # 종속변수의 col
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [76]:
## 모델 학습
model.fit(독립, 종속, epochs=10, verbose=0) # epochs는 학습 수
model.fit(독립, 종속, epochs=10) # epochs는 학습 수

Epoch 1/10
1/1 [==============================] - 0s 4ms/step - loss: 0.3064 - accuracy: 0.8438
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 0.3063 - accuracy: 0.8438
Epoch 3/10
1/1 [==============================] - 0s 3ms/step - loss: 0.3064 - accuracy: 0.8438
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 0.3064 - accuracy: 0.8438
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 0.3064 - accuracy: 0.8438
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: 0.3064 - accuracy: 0.8438
Epoch 7/10
1/1 [==============================] - 0s 3ms/step - loss: 0.3063 - accuracy: 0.8438
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 0.3062 - accuracy: 0.8438
Epoch 9/10
1/1 [==============================] - 0s 4ms/step - loss: 0.3062 - accuracy: 0.8438
Epoch 10/10
1/1 [==============================] - 0s 3ms/step - loss: 0.3062 - accuracy: 0.8438


In [80]:
model.predict([[0, 60, 40, 40]])

array([[0.0000000e+00, 0.0000000e+00, 7.4926374e-25, 5.2679330e-16,
        3.4045706e-38, 3.2395806e-38, 0.0000000e+00, 1.0601262e-34,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 2.1793699e-38, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 9.5307199e-35, 7.7137027e-29,
        0.0000000e+00, 0.0000000e+00, 1.9735566e-25, 0.0000000e+00,
        0.0000000e+00, 5.6146159e-25, 5.4148604e-06, 7.6698935e-14,
        9.9999452e-01, 3.3145948e-16, 1.0673189e-07]], dtype=float32)

In [83]:
result_predict = model.predict([[0, 60, 40, 50]])[0]
result_name = ['name_거문오름',
       'name_검은오름', 'name_고근산', 'name_군산', 'name_궷물오름', 'name_다랑쉬', 'name_도두봉',
       'name_따라비오름', 'name_물메(수산봉)', 'name_물영아리', 'name_민오름', 'name_백약이오름',
       'name_붉은오름', 'name_산굼부리', 'name_새별오름', 'name_서우봉', 'name_성산일출봉',
       'name_송악산', 'name_수월봉', 'name_아끈다랑쉬', 'name_아부오름', 'name_안돌오름',
       'name_영주산', 'name_용눈이오름', 'name_용머리', 'name_이승이', 'name_저지오름',
       'name_정물오름', 'name_지미봉', 'name_큰바리메오름']

result = list(zip(result_predict*100, result_name))
result

[(0.0, 'name_거문오름'),
 (0.0, 'name_검은오름'),
 (3.4738193e-28, 'name_고근산'),
 (0.0, 'name_군산'),
 (0.0, 'name_궷물오름'),
 (0.0, 'name_다랑쉬'),
 (0.0, 'name_도두봉'),
 (0.0, 'name_따라비오름'),
 (0.0, 'name_물메(수산봉)'),
 (0.0, 'name_물영아리'),
 (0.0, 'name_민오름'),
 (0.0, 'name_백약이오름'),
 (0.0, 'name_붉은오름'),
 (0.0, 'name_산굼부리'),
 (0.0, 'name_새별오름'),
 (0.0, 'name_서우봉'),
 (0.0, 'name_성산일출봉'),
 (0.0, 'name_송악산'),
 (0.0, 'name_수월봉'),
 (0.0, 'name_아끈다랑쉬'),
 (0.0, 'name_아부오름'),
 (0.0, 'name_안돌오름'),
 (0.0, 'name_영주산'),
 (0.0, 'name_용눈이오름'),
 (0.0, 'name_용머리'),
 (0.0, 'name_이승이'),
 (0.0, 'name_저지오름'),
 (4.8624133e-14, 'name_정물오름'),
 (1.4663941e-10, 'name_지미봉'),
 (0.0, 'name_큰바리메오름')]

In [84]:
sorted(result, key=lambda x:x[0], reverse=True)

[(1.4663941e-10, 'name_지미봉'),
 (4.8624133e-14, 'name_정물오름'),
 (3.4738193e-28, 'name_고근산'),
 (0.0, 'name_거문오름'),
 (0.0, 'name_검은오름'),
 (0.0, 'name_군산'),
 (0.0, 'name_궷물오름'),
 (0.0, 'name_다랑쉬'),
 (0.0, 'name_도두봉'),
 (0.0, 'name_따라비오름'),
 (0.0, 'name_물메(수산봉)'),
 (0.0, 'name_물영아리'),
 (0.0, 'name_민오름'),
 (0.0, 'name_백약이오름'),
 (0.0, 'name_붉은오름'),
 (0.0, 'name_산굼부리'),
 (0.0, 'name_새별오름'),
 (0.0, 'name_서우봉'),
 (0.0, 'name_성산일출봉'),
 (0.0, 'name_송악산'),
 (0.0, 'name_수월봉'),
 (0.0, 'name_아끈다랑쉬'),
 (0.0, 'name_아부오름'),
 (0.0, 'name_안돌오름'),
 (0.0, 'name_영주산'),
 (0.0, 'name_용눈이오름'),
 (0.0, 'name_용머리'),
 (0.0, 'name_이승이'),
 (0.0, 'name_저지오름'),
 (0.0, 'name_큰바리메오름')]

In [85]:
def 제곱(x):
    return x**2

제곱람다 = lambda x:x**2
제곱람다(10)

100

In [89]:
test = [('일하나', 34, 100, 68),
        ('이하나', 84, 32, 32),
        ('삼하나', 54, 48, 78),
        ('사하나', 97, 91, 21),
        ('오하나', 92, 84, 11)]

In [91]:
sorted(test, key=lambda x:x[1], reverse=True)

[('사하나', 97, 91, 21),
 ('오하나', 92, 84, 11),
 ('이하나', 84, 32, 32),
 ('삼하나', 54, 48, 78),
 ('일하나', 34, 100, 68)]

In [94]:
result[0][1][5:]


'거문오름'

In [99]:
추천리스트 = []
for i in range(5):
    추천리스트.append([result[i][1][5:]])

추천리스트

[['거문오름'], ['검은오름'], ['고근산'], ['군산'], ['궷물오름']]

In [100]:
result

[(0.0, 'name_거문오름'),
 (0.0, 'name_검은오름'),
 (3.4738193e-28, 'name_고근산'),
 (0.0, 'name_군산'),
 (0.0, 'name_궷물오름'),
 (0.0, 'name_다랑쉬'),
 (0.0, 'name_도두봉'),
 (0.0, 'name_따라비오름'),
 (0.0, 'name_물메(수산봉)'),
 (0.0, 'name_물영아리'),
 (0.0, 'name_민오름'),
 (0.0, 'name_백약이오름'),
 (0.0, 'name_붉은오름'),
 (0.0, 'name_산굼부리'),
 (0.0, 'name_새별오름'),
 (0.0, 'name_서우봉'),
 (0.0, 'name_성산일출봉'),
 (0.0, 'name_송악산'),
 (0.0, 'name_수월봉'),
 (0.0, 'name_아끈다랑쉬'),
 (0.0, 'name_아부오름'),
 (0.0, 'name_안돌오름'),
 (0.0, 'name_영주산'),
 (0.0, 'name_용눈이오름'),
 (0.0, 'name_용머리'),
 (0.0, 'name_이승이'),
 (0.0, 'name_저지오름'),
 (4.8624133e-14, 'name_정물오름'),
 (1.4663941e-10, 'name_지미봉'),
 (0.0, 'name_큰바리메오름')]