<a href="https://colab.research.google.com/github/rosa2070/TensorFlow01_25/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## TensorFlow로 알아보는 딥러닝



In [1]:
import tensorflow as tf
import pandas as pd

In [2]:
data = {
    '창업연차' : [4, 5, 6, 7, 8],
    '매출액(억)' : [8, 10, 12, 14, 16]
}

df = pd.DataFrame(data)
df

창업연차  매출액(억)
0     4       8
1     5      10
2     6      12
3     7      14
4     8      16

In [4]:
독립 = df[['창업연차']] # 원인
종속 = df[['매출액(억)']] # 결과

독립.shape, 종속.shape

((5, 1), (5, 1))

In [6]:
## 모델 준비(y = wx + b)
X = tf.keras.layers.Input(shape=[1]) # 독립변수의 col
Y = tf.keras.layers.Dense(1)(X) # 종속변수의 col
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse') 
#MSE(mean squared error) : 회귀 용도의 딥러닝 모델을 훈련시킬 때 사용되는 손실 함수

In [7]:
model.fit(독립, 종속, epochs = 10)

Epoch 1/10
1/1 [==============================] - 1s 520ms/step - loss: 160.4822
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 159.9109
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 159.4973
Epoch 4/10
1/1 [==============================] - 0s 4ms/step - loss: 159.1517
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 158.8453
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: 158.5648
Epoch 7/10
1/1 [==============================] - 0s 4ms/step - loss: 158.3029
Epoch 8/10
1/1 [==============================] - 0s 4ms/step - loss: 158.0550
Epoch 9/10
1/1 [==============================] - 0s 4ms/step - loss: 157.8179
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 157.5895


In [8]:
model.predict([10])

array([[-0.36012468]], dtype=float32)

In [9]:
model.predict(독립)

array([[-0.13366769],
       [-0.17141052],
       [-0.20915335],
       [-0.24689619],
       [-0.28463903]], dtype=float32)

In [10]:
#y = wx + b

model.get_weights()

[array([[-0.03774283]], dtype=float32), array([0.01730363], dtype=float32)]

In [12]:
-0.03774283 * 10 + 0.01730363

-0.36012467

In [13]:
model.fit(독립, 종속, epochs = 10000, verbose=0)
model.fit(독립, 종속, epochs = 10)

Epoch 1/10
1/1 [==============================] - 0s 4ms/step - loss: 1.2749e-05
Epoch 2/10
1/1 [==============================] - 0s 8ms/step - loss: 1.2750e-05
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 1.2749e-05
Epoch 4/10
1/1 [==============================] - 0s 3ms/step - loss: 1.2750e-05
Epoch 5/10
1/1 [==============================] - 0s 4ms/step - loss: 1.2749e-05
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 1.2750e-05
Epoch 7/10
1/1 [==============================] - 0s 3ms/step - loss: 1.2749e-05
Epoch 8/10
1/1 [==============================] - 0s 3ms/step - loss: 1.2750e-05
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 1.2749e-05
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 1.2750e-05


In [14]:
model.predict(독립)

array([[ 8.002501],
       [10.003   ],
       [12.0035  ],
       [14.004   ],
       [16.0045  ]], dtype=float32)

In [15]:
model.predict([10])

array([[20.005499]], dtype=float32)

In [16]:
#y = wx + b

model.get_weights()

[array([[2.0004997]], dtype=float32), array([0.00050134], dtype=float32)]

In [17]:
2.0004997 * 10 + 0.00050134

20.005498340000003